# Generated by Django 6.0.5 on 2026-05-22 10:16

import Source.certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='template_file',
            field=models.FileField(upload_to='course_templates/', validators=[Source.certificates.models.validate_docx_extension]),
        ),
    ]
