# Generated by Django 6.0.5 on 2026-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_course_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text="Internal course code shown on the certificate, e.g. 'BLS 1260'", max_length=50),
        ),
    ]
