# Generated by Django 6.0.5 on 2026-05-22 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField()),
                ('saqa_id', models.CharField(max_length=20)),
                ('accreditation_body', models.CharField(max_length=200)),
                ('validity_months', models.PositiveIntegerField(default=36)),
                ('template_file', models.FileField(upload_to='course_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('id_type', models.CharField(choices=[('sa_id', 'SA ID'), ('passport', 'Passport')], default='sa_id', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=20, unique=True)),
                ('learner_name_snapshot', models.CharField(max_length=200)),
                ('course_name_snapshot', models.CharField(max_length=200)),
                ('training_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('assessor_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled'), ('reissued', 'Reissued')], default='issued', max_length=20)),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='certificates.certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.learner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled'), ('reissued', 'Reissued'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='certificates.certificate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
