# Generated by Django 6.0.5 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_course_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatenumbersequence",
            name="last_number",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
